generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display:  [id, =username, created_at, last_login, is_active, is_super_admin]
        sort:     [id, asc]
      filter:
        display:  [username, is_active, is_super_admin]
      form:
        class:    sfGuardUserAdminForm
        display:
          NONE:           [username, password, password_again, is_active]
          "Permissions":  [is_super_admin, sf_guard_user_permission_list]
          "Profile":      [email]
      edit:    ~
      new:     ~
